GRANT SELECT, UPDATE, DELETE ON CUSTOMER TO MARKERTL;
GRANT SELECT, UPDATE, DELETE ON DISH TO MARKERTL;
GRANT SELECT, UPDATE, DELETE ON DRIVER TO MARKERTL;
GRANT SELECT, UPDATE, DELETE ON "ORDER" TO MARKERTL;
GRANT SELECT, UPDATE, DELETE ON ORDER_DISH TO MARKERTL;
GRANT SELECT, UPDATE, DELETE ON RESTAURANT TO MARKERTL;
GRANT SELECT, UPDATE, DELETE ON RESTAURANT_CERTIFICATION TO MARKERTL;

GRANT SELECT, UPDATE, DELETE ON VIEWA TO MARKERTL;
GRANT SELECT, UPDATE, DELETE ON VIEWB TO MARKERTL;
GRANT SELECT, UPDATE, DELETE ON VIEWC TO MARKERTL;
GRANT SELECT, UPDATE, DELETE ON VIEWD TO MARKERTL;
GRANT SELECT, UPDATE, DELETE ON VIEWE TO MARKERTL;
GRANT SELECT, UPDATE, DELETE ON VIEWF TO MARKERTL;
GRANT SELECT, UPDATE, DELETE ON VIEWG TO MARKERTL;
GRANT SELECT, UPDATE, DELETE ON VIEWH TO MARKERTL;
GRANT SELECT, UPDATE, DELETE ON VIEWI TO MARKERTL;
GRANT SELECT, UPDATE, DELETE ON VIEWJ TO MARKERTL;
commit;